### ISSUE TITLE
Failing to pass in paths results in confusing error message

### ISSUE THREAD

**Issue by quattro** [MarcoGorelli/cython-lint#99]
Hi 👋 , thanks for the great tool! I noticed that failing to pass in a path or paths to `cython-lint` results in the confusing error, 

```python
Traceback (most recent call last):
  File "/Users/nicholas/micromamba/bin/cython-lint", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/nicholas/micromamba/lib/python3.11/site-packages/cython_lint/cython_lint.py", line 898, in main
    config = {k.replace('-', '_'): v for k, v in _get_config(paths).items()}
                                                 ^^^^^^^^^^^^^^^^^^
  File "/Users/nicholas/micromamba/lib/python3.11/site-packages/cython_lint/cython_lint.py", line 852, in _get_config
    root = pathlib.Path(os.path.commonpath(paths))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 531, in commonpath
ValueError: commonpath() arg is an empty sequence
```

I believe a simple remedy for this would be to replace the [line](https://github.com/MarcoGorelli/cython-lint/blob/9e1d65daed6a23ff32e1893b749607432fd6d8f1/cython_lint/cython_lint.py#L871)
```python 
parser.add_argument('paths', nargs='*')
```

with
```python
parser.add_argument('paths', nargs='+')
```

This should produce a more helpful error message with users make silly mistakes (like me).

**Comment by MarcoGorelli** [comment]
Sure, a pr would be welcome thanks
